import React, { Fragment } from 'react'

import BrandLink from '../components/BrandLink'
import FactNumber from '../components/FactNumber'

const About = () => {
    return (
        <Fragment>
            <div className="flex items-center">
                <div className="relative my-20 mx-auto">
                    <div className="absolute bg-earthYellowLight h-14 rounded-full top-0 w-14 -z-1"></div>
                    <BrandLink classes="text-6xl ml-5" />
                </div>
            </div>
            <div className=" text-justify py-10">
                <div className="mx-auto w-2/3">
                    <p className="mb-4">
                        Our store is the premier destination for quality clothes, jewelry, and electronics. With a broad
                        assortment of over 100,000 unique items across online platforms and physical locations, we
                        inspire customers to express their unique style and passion.
                    </p>
                    <p>
                        The heart of our strategy lies in the continued growth of our expansive e-commerce business. In
                        the fiscal year 2022/2023, we generated sales of 4 billion dollars from a diverse portfolio of
                        products including clothing, jewelry, electronics, and accessories.
                        <span className="font-alegreyaSans text-2xl font-semibold"> #StyleExpression</span>
                    </p>
                </div>
            </div>

            <div className="bg-earthYellowLight">
                <div className="flex flex-col md:flex-row space-y-10 md:space-y-0 py-10 w-3/4 mx-auto">
                    {/* Facts and figures */}
                    <FactNumber
                        icon={'people'}
                        number="125"
                        title="Style Gurus"
                        description="are dedicated to making our customers feel stylish and confident"
                    />
                    <FactNumber
                        icon={'revenue'}
                        number="4"
                        title="Billion Dollars"
                        description="revenue was generated by our store in the 2022/23 financial year"
                    />
                    <FactNumber
                        icon={'shop'}
                        number="100,000"
                        title="Unique Items"
                        description="available to suit your unique style, both online and in stores"
                    />
                </div>
            </div>
            <div className="text-center w-2/3 mx-auto my-20">
                <h4 className="font-alegreyaSans text-2xl mb-4">Allures Ecomm Inc</h4>
                <p>Head Office Location: Our-Street 123 40235 City</p>
                <p>
                    You can reach us by email at: service@allurescomm.com. Thanks for shopping with us! We appreciate
                    your business.
                </p>
            </div>
        </Fragment>
    )
}

export default About
